# Generated by Django 4.2.9 on 2025-01-31 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0001_initial"),
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="people.person"
            ),
        ),
    ]
